version: '3.8'

services:
  db_container:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: menudigital
    ports:
      - "3308:3306"
    networks:
      - menudigital_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db_container
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8091:80"
    networks:
      - menudigital_network
    depends_on:
      - db_container

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      DB_URL: ${DB_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      rutaimagenes: ${rutaimagenes}
      usuarioroot: ${usuarioroot}
      usuariopass: ${usuariopass}
    networks:
      - menudigital_network
    depends_on:
      db_container:
        condition: service_healthy

networks:
  menudigital_network:
    name: menudigital_network
    driver: bridge